# Generated by Django 2.2.2 on 2019-08-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectusers',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='projectversions',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelTable(
            name='projectusers',
            table='project_users',
        ),
        migrations.AlterModelTable(
            name='projectversions',
            table='project_versions',
        ),
    ]
