# Generated by Django 2.2.2 on 2019-08-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_auto_20190821_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectversions',
            name='version',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
