# Generated by Django 2.2.2 on 2019-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_auto_20190821_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_on',
            field=models.DateField(null=True),
        ),
    ]
