# Generated by Django 2.2.2 on 2019-08-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_auto_20190821_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='team_members',
        ),
    ]
