# Generated by Django 2.2.2 on 2019-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_remove_projects_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusers',
            name='role',
            field=models.CharField(choices=[('BACK-END DEVELOPER', 'DEVELOPERS'), ('FRONT-END DEVELOPER', 'DEVELOPERS'), ('TEAM_LEAD', 'TEAM_LEAD'), ('PROJECT_MANAGER', 'PROJECT_MANAGER'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('DEVOPS', 'DEVOPS'), ('DATA_OPERATORS', 'DATA_OPERATORS'), ('DATA_SCIENTIST', 'DATA_SCIENTIST'), ('MANUAL TESTER', 'MANUAL TESTER'), ('AUTOMATION TESTER', 'AUTOMATION TESTER')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('BACK-END DEVELOPER', 'DEVELOPERS'), ('FRONT-END DEVELOPER', 'DEVELOPERS'), ('TEAM_LEAD', 'TEAM_LEAD'), ('PROJECT_MANAGER', 'PROJECT_MANAGER'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('DEVOPS', 'DEVOPS'), ('DATA_OPERATORS', 'DATA_OPERATORS'), ('DATA_SCIENTIST', 'DATA_SCIENTIST'), ('MANUAL TESTER', 'MANUAL TESTER'), ('AUTOMATION TESTER', 'AUTOMATION TESTER')], max_length=255),
        ),
    ]
